"""Shared constants for MAX Bot API clients."""

DEFAULT_API_BASE_URL = "https://platform-api.max.ru"
MAX_MESSAGE_LENGTH = 4096
DEDUP_WINDOW_SECONDS = 300
DEDUP_MAX_SIZE = 1000
DEFAULT_TIMEOUT_SECONDS = 30
DEFAULT_HERMES_TIMEOUT = 120

# Update types
UPDATE_MESSAGE_CREATED = "message_created"
UPDATE_MESSAGE_EDITED = "message_edited"
UPDATE_MESSAGE_REMOVED = "message_removed"
UPDATE_MESSAGE_CALLBACK = "message_callback"
UPDATE_BOT_ADDED = "bot_added"
UPDATE_BOT_REMOVED = "bot_removed"
UPDATE_BOT_STARTED = "bot_started"
UPDATE_CHAT_CREATED = "chat_created"
UPDATE_USER_ADDED = "user_added"
UPDATE_USER_REMOVED = "user_removed"
UPDATE_CHAT_TITLE_CHANGED = "chat_title_changed"

SUPPORTED_UPDATE_TYPES = [
    UPDATE_MESSAGE_CREATED,
    UPDATE_MESSAGE_EDITED,
    UPDATE_MESSAGE_REMOVED,
    UPDATE_MESSAGE_CALLBACK,
    UPDATE_BOT_ADDED,
    UPDATE_BOT_REMOVED,
    UPDATE_BOT_STARTED,
    UPDATE_CHAT_CREATED,
    UPDATE_USER_ADDED,
    UPDATE_USER_REMOVED,
    UPDATE_CHAT_TITLE_CHANGED,
]

# Attachment types
ATTACHMENT_IMAGE = "image"
ATTACHMENT_VIDEO = "video"
ATTACHMENT_AUDIO = "audio"
ATTACHMENT_FILE = "file"
ATTACHMENT_VOICE = "voice"
ATTACHMENT_CONTACT = "contact"
ATTACHMENT_LOCATION = "location"
ATTACHMENT_STICKER = "sticker"
ATTACHMENT_INLINE_KEYBOARD = "inline_keyboard"

MEDIA_TYPES = {ATTACHMENT_IMAGE, ATTACHMENT_VIDEO, ATTACHMENT_AUDIO, ATTACHMENT_VOICE}

# Chat types
CHAT_TYPE_DIALOG = "dialog"
CHAT_TYPE_GROUP = "group"
CHAT_TYPE_CHANNEL = "channel"
CHAT_TYPE_SUPERGROUP = "supergroup"

GROUP_CHAT_TYPES = {CHAT_TYPE_GROUP, CHAT_TYPE_CHANNEL, CHAT_TYPE_SUPERGROUP}
